version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy:v3
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user:v3
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed:v3
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:v6